/* DO NOT EDIT THIS FILE - it is machine generated */
#include "/usr/lib/jvm/java-8-oracle/include/jni.h"
/* Header for class com_example_file_OpenFileLowLevel */

#ifndef _Included_com_example_file_OpenFileLowLevel
#define _Included_com_example_file_OpenFileLowLevel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_file_OpenFileLowLevel
 * Method:    acquireLock
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_file_OpenFileLowLevel_acquireLock(JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_file_OpenFileLowLevel
 * Method:    releaseLock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_file_OpenFileLowLevel_releaseLock(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
